This is a way to study NumPy library, I'll be referring freecodecamp.org


What is Numpy?

In [2]:
print("NumPy is a multidimensional array library")

NumPy is a multidimensional array library


How Lists and NumPy differ? <br>
Lists - slow, built in int-type consist of - object value, type, reference count, and size
<br><br>
NumPy- fast, uses fixed types, No type checking when iterating through objects,contiguous memory

operations - Insertion, Deletion, Appending, Concatenation, etc.

Applications - Mathematics, Plotting(matplotlib), Backend, Machine Learning,

Lets Go!

In [3]:
#If installing for the first time, then do "pip install numpy" 
# else go for import

In [4]:
import numpy as np

In [5]:
# The Basics
a = np.array([1 , 2 ,3])
print(a) #one dimensional array

[1 2 3]


In [6]:
# what about 2D array?
b = np.array([[1 , 2 , 3],[4 , 5 , 6]])
print(b) # this is not limited to 2D - it's multi Dimensional

[[1 2 3]
 [4 5 6]]


In [7]:
# Get dimension of array
print(a.ndim)#dimension of a
print(b.ndim)#dimension of b

1
2


In [8]:
# Shape function 
a.shape #form of rows and columns(r,c)

(3,)

In [9]:
b.shape # 2rows and 3 cols

(2, 3)

In [10]:
# Get Type(datatype)
a.dtype,b.dtype

(dtype('int32'), dtype('int32'))

In [11]:
# How to get size it takes?
a.itemsize

4

In [12]:
# We can also specify the datatype like int16, int32
c=np.array([1,2,3],dtype='int16')
print(c)
print(c.dtype)
print(c.itemsize)

[1 2 3]
int16
2


In [13]:
# How to get total size?
#two ways

In [14]:
 #way one
a.size*a.itemsize

12

In [15]:
#way two
a.nbytes

12

#### Accessing/Changing specific elements, rows, columns, etc.

In [16]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [17]:
#lets examine the shape
a.shape #that is 2 rows and 6 columns

(2, 6)

In [18]:
# Get a specific element
a[1,5] #that is index starts from 0

12

In [19]:
# fetch a specific row
a[1]

array([ 7,  8,  9, 10, 11, 12])

In [20]:
# fetch a specific column
a[:,1] #

array([2, 8])

In [21]:
#[startindex:endindex:stepsize]
a[0,1:4:1]

array([2, 3, 4])

In [22]:
#replace an element
print(a[0,1])
a[0,1]=5
print(a[0,1])

2
5


In [23]:
# we can also replace like:
newA=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(newA)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [24]:
newA[:,1]=[9,9]
print(newA)
#both column one has changed values

[[ 1  9  3  4  5  6]
 [ 7  9  9 10 11 12]]


In [25]:
#Working with 3D arrays
new = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(new)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
# Get specific element
new[0,1,1]

4

In [27]:
new[:,:,0]

array([[1, 3],
       [5, 7]])

In [28]:
# replacing in 3D(working can be done in same dimension)
new[0,1,:]=[9,9]
new

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [7, 8]]])

### Initializing Different Types of Arrays

In [29]:
# All zeroes matrix
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
np.zeros([5,2,2])# you can specify dimensions as increasing

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [31]:
#All 1's matrix
np.ones([2,4,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
#Data type can specified: Here 'int32'
np.ones((1,3,2), dtype ='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]]])

In [33]:
#np.full?
np.full([2,2],99)

array([[99, 99],
       [99, 99]])

In [34]:
# Datatype can be specified
np.full([3,3,3],99,dtype='float16')

array([[[99., 99., 99.],
        [99., 99., 99.],
        [99., 99., 99.]],

       [[99., 99., 99.],
        [99., 99., 99.],
        [99., 99., 99.]],

       [[99., 99., 99.],
        [99., 99., 99.],
        [99., 99., 99.]]], dtype=float16)

In [35]:
# np.full_like
np.full_like(new,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [36]:
# alternative for np.full_like can be done as 
np.full(new.shape,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [37]:
# Random Decimal numbers
np.random.rand(4,2,2)

array([[[0.54683741, 0.31381936],
        [0.83404023, 0.76483382]],

       [[0.4262546 , 0.63042834],
        [0.77556728, 0.97036266]],

       [[0.94446675, 0.20617603],
        [0.37203497, 0.14529926]],

       [[0.02686314, 0.14750469],
        [0.9825596 , 0.03358343]]])

In [38]:
# np.random.random_sample() 
np.random.random_sample(new.shape)

array([[[0.42919658, 0.44410189],
        [0.26358088, 0.05588799]],

       [[0.50383011, 0.95630817],
        [0.76993711, 0.44479065]]])

In [39]:
# Random Integers
np.random.randint(5, size=(3,3))

array([[3, 4, 3],
       [3, 2, 2],
       [1, 4, 3]])

In [40]:
np.random.randint(1,5, size=(3,3))

array([[1, 2, 1],
       [4, 1, 2],
       [1, 1, 3]])

In [41]:
# Identity Matrix
np.identity(3, dtype='int32') #I just specified the dtype not actually required.

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [42]:
np.identity(3) # without dtype

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
#np.repeat()
newarr=np.array([[1,2,3]])
n1=np.repeat(newarr,3,axis=0)
print(n1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Assignment

1  1  1  1  1<br>
1  0  0  0  1<br>
1  0  9  0  1<br>
1  0  0  0  1<br>
1  1  1  1  1

In [44]:
# Assignment
new=np.ones((5,5),dtype='int32')
print(new)
new[(1,2,3),1:-1]=0
print(new)
new[2,2]=9
print(new)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [45]:
# Alternative method
op=np.ones((5,5))
print(op)
ze=np.zeros((3,3))
print(ze)
ze[1,1]=9
print(ze)
op[1:-1,1:-1]=ze
print(op)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
# Caution while copying arrays
a=np.array([2,3,4])
print(a)
b=a # a.copy can be used instead
b[0]=100
print(b)
print(a)

[2 3 4]
[100   3   4]
[100   3   4]


#### Mathematics

In [47]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [48]:
a=a+2
a

array([3, 4, 5, 6, 7, 8])

In [49]:
a=a-2
a

array([1, 2, 3, 4, 5, 6])

In [50]:
a=a*2
a

array([ 2,  4,  6,  8, 10, 12])

In [51]:
a=a/2
a

array([1., 2., 3., 4., 5., 6.])

In [52]:
b=a
a+b

array([ 2.,  4.,  6.,  8., 10., 12.])

In [53]:
x=np.array([1,2,3])
x**2

array([1, 4, 9])

In [54]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

In [72]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 ])

#### Linear Algebra

In [105]:
# Matrix multiplication
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [70]:
# Determinant of Identity Matrix
c=np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

#### Statistics

In [79]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.min(stats)

1

In [81]:
np.max(stats)

6

In [83]:
# row basis sort
np.min(stats, axis=1)

array([1, 4])

In [84]:
np.max(stats,axis=1)

array([3, 6])

In [85]:
np.sum(stats) #sum

21

#### Reorganizing Arrays

In [86]:
before =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(before)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [87]:
# analyse shape
print(before.shape)

(2, 5)


In [88]:
# Reshape
after=before.reshape((5,2))
print(after)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [90]:
# Vertical Stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [93]:
# Horizontal Stack
h1=np.ones((3,4))
h2=np.zeros((3,4))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

<strong>Miscellaneous</strong>

Load data from file

In [98]:
files=np.genfromtxt('test.txt',delimiter=',')
files=files.astype('int32')
files

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  4,  5,  0,  2,  5,  5,  8,  8,  1]])

Boolean Masking and Advanced Indexing

In [99]:
files>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [100]:
files<=10

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [102]:
files[files<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 4, 5, 0, 2, 5, 5, 8, 8, 1])

In [104]:
np.any(files>5, axis =0)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])